name: CI

on: [pull_request, push]

jobs:
  Test:
    env:
      JULIA_VERSION_FOR_COVERAGE: 1.6.0
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.6.0]
        julia-arch: [x64]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: runtests - basic
        run: |
             echo "JULIA_VERSION_FOR_COVERAGE=${{ JULIA_VERSION_FOR_COVERAGE }}" >> $GITHUB_ENV
             true

  Coverage:
    needs: Test
    if: github.event.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: coverage
        run: |
             echo "JULIA_VERSION_FOR_COVERAGE ${{ env.JULIA_VERSION_FOR_COVERAGE }}"
      - uses: codecov/codecov-action@v1
